name 'dbserver'
maintainer 'Puneet Sachdev'
maintainer_email 'puneet.sachdev@gmail.com'
license 'all_rights'
description 'Installs/Configures dbserver'
long_description 'Installs/Configures dbserver'
version '0.1.1'
depends 'apt', '= 3.0.0'
depends 'mysql', '= 7.0.0'
