name 'apiserver'
maintainer 'Puneet Sachdev'
maintainer_email 'puneet.sachdev@gmail.com'
license 'all_rights'
description 'Installs/Configures apiserver'
long_description 'Installs/Configures apiserver'
version '0.1.10'
depends 'apt', '= 3.0.0'
depends 'java'
